.Dd 2009-05-17
.Dt istatserver.conf 5
.Os
.Sh NAME
.Nm istatserver.conf
.Nd configuration file for istatserver

.Sh OPTIONS
.Bl -tag -width -indent-three
.It network_addr
Address to bind (default: 0.0.0.0)

.It network_port
Port to bind (default: 5109)

.It server_code
Lock code needed when connecting to the server for the first time.

.It server_socket
Location of the unix socket. (default: /tmp/istatserver.sock)

.It server_pid
Location of the pid. (default: /var/run/istatserver.pid)

.It server_user
User to switch to when entering daemon mode. It's not recommended to use high privilaged users like root due to security reasons. Defaults to root if the user doesn't exist. (default: istat)

.It server_group
Group to switch to when entering daemon mode. Defaults to root if the group doesn't exist. (default: istat)

.It disable_history_storage
Set to 1 if you want to disable history storage (not recommended unless you have very limited disk space).


.It disk_disable_filtering
Set to 1 if you want to disable all mount path based disk filtering (excludes filesystems that you are unlikely to want to monitor).

.It disk_mount_path_label
Set to 1 if you want to use mount path as label instead of the device name.
.It disk_rename_label
Set custom disk label. Will override all other labels. You can use either the device name or mount path:

disk_rename_label        /dev/sda1  "root"

disk_rename_label        /home      "home"
.El
.Sh SEE ALSO
.Xr istatserver 1
